version: '3'
services:
  vnstat-dashboard:
    image: php:7.0-apache
    network_mode: "host"
    container_name: vnstat-dashboard
    volumes:
          - /var/lib/vnstat:/var/lib/vnstat
          - /usr/bin/vnstat:/usr/bin/vnstat
          - /etc/localtime:/etc/localtime:ro
          - /var/run/docker.sock:/var/run/docker.sock
          - ./dashboard:/var/www/html/vnstat/

  # vnstat:
  #   image: vimagick/vnstat:latest
  #   volumes:
  #     - ./data:/var/lib/vnstat
  #   network_mode: host
  #   restart: always